version: '3'
services: 
    mysql:
        image: mysql:5.7
        container_name: db_mysql
        env_file: ./mysql/mysql.env
        environment: 
            - TZ=Asia/Tokyo
        ports: 
            - '3306:3306'
        volumes: 
            - ./mysql/conf:/etc/mysql/conf.d:ro
            - mysqldata:/var/lib/mysql
        networks: 
            - default
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        tty: true
        ports: 
            - '3000:3000'
        volumes: 
            - ./src:/app
            - /app/node_modules
        networks: 
            - default
        depends_on: 
            - mysql
volumes: 
    mysqldata: